import express from 'express';
import request from 'supertest';
import marginalityRoutes from '../src/routes/marginalityRoutes';
import { prisma } from '../src/db';

const app = express();
app.use(express.json());
app.use('/api/marginality', marginalityRoutes);

describe('Marginality API CRUD Operations', () => {
  let createdTestId: string;
  let createdUserId = "demo-user";
  let realCategoryId: string;
  let realQuestionId: string;

  beforeAll(async () => {
    await prisma.marginalityTestResponse.deleteMany();
    await prisma.marginalityTest.deleteMany();
    
    await prisma.user.upsert({
      where: { id: "demo-user" },
      update: {},
      create: {
        id: "demo-user",
        email: "demo@system.local",
        username: "Test User",
        passwordHash: "hash",
        avatarUrl: "/logo.png"
      }
    });
  });

  afterAll(async () => {
    await prisma.$disconnect();
  });

  it('1. POST /api/marginality - Should create a new test', async () => {
    const newTest = {
      title: "Test Marginality Profile",
      topic: "Testing",
      description: "A test generated by Jest.",
      ownerId: createdUserId,
      categoryDefinitions: [ 
        { 
          key: "cat1", 
          label: "Category A", 
          leftLabel: "Low", 
          rightLabel: "High",
          inputType: "select"
        }
      ],
      questions: [
        { 
          id: "q1", 
          text: "Do you like writing tests?", 
          categoryId: "cat1", 
        }
      ]
    };

    const res = await request(app).post('/api/marginality').send(newTest);
    
    if (res.status !== 201) console.log("TEST CREATION ZOD ERROR:", JSON.stringify(res.body.errors, null, 2));

    expect(res.status).toBe(201);
    expect(res.body).toHaveProperty('id');
    expect(res.body.title).toBe("Test Marginality Profile");
    expect(res.body.categoryDefinitions.length).toBe(1);
    
    createdTestId = res.body.id;
  });

  it('2. GET /api/marginality - Should fetch paginated tests', async () => {
    const res = await request(app).get('/api/marginality');

    expect(res.status).toBe(200);
    expect(res.body).toHaveProperty('data');
    expect(res.body.data.length).toBeGreaterThan(0);
    expect(res.body.data[0].id).toBe(createdTestId);
  });

  it('3. GET /api/marginality/:id - Should fetch a specific test', async () => {
    const res = await request(app).get(`/api/marginality/${createdTestId}`);

    expect(res.status).toBe(200);
    expect(res.body.id).toBe(createdTestId);
    expect(res.body.questions.length).toBe(1);

    realCategoryId = res.body.categoryDefinitions[0].id;
    realQuestionId = res.body.questions[0].id;
  });

  it('4. POST /api/marginality/responses - Should submit a response', async () => {
    const newResponse = {
      testId: createdTestId,
      userId: createdUserId,
      categoryValues: {
        [realCategoryId]: 75 
      },
      votes: [
        { questionId: realQuestionId, agreement: 5 } 
      ]
    };

    const res = await request(app).post('/api/marginality/responses').send(newResponse);
    
    if (res.status !== 201) console.log("RESPONSE CREATION ZOD ERROR:", JSON.stringify(res.body.errors, null, 2));

    expect(res.status).toBe(201);
    expect(res.body.testId).toBe(createdTestId);
    expect(res.body.userId).toBe(createdUserId);
  });

  it('5. GET /api/marginality/responses - Should fetch all responses', async () => {
    const res = await request(app).get('/api/marginality/responses');

    expect(res.status).toBe(200);
    expect(Array.isArray(res.body)).toBe(true);
    expect(res.body.length).toBeGreaterThan(0);
  });

  it('6. DELETE /api/marginality/:id - Should delete the test', async () => {
    await prisma.marginalityTestResponse.deleteMany({
      where: { testId: createdTestId }
    });

    const res = await request(app).delete(`/api/marginality/${createdTestId}`);
    expect(res.status).toBe(204);

    const fetchRes = await request(app).get(`/api/marginality/${createdTestId}`);
    expect(fetchRes.status).toBe(404);
  });

  describe('Marginality API - Sabotage Tests (500 Errors)', () => {
    afterEach(() => {
      jest.restoreAllMocks();
    });

    it('Should trigger a 500 error on GET all tests', async () => {
      jest.spyOn(prisma.marginalityTest, 'findMany').mockRejectedValue(new Error('Simulated DB Crash'));

      const res = await request(app).get('/api/marginality');
      expect(res.status).toBe(500);
    });

    it('Should trigger a 500 error on GET test by ID', async () => {
      jest.spyOn(prisma.marginalityTest, 'findUnique').mockRejectedValue(new Error('Simulated DB Crash'));

      const res = await request(app).get('/api/marginality/fake-id');
      expect(res.status).toBe(500);
    });

    it('Should trigger a 500 error on GET responses', async () => {
      jest.spyOn(prisma.marginalityTestResponse, 'findMany').mockRejectedValue(new Error('Simulated DB Crash'));

      const res = await request(app).get('/api/marginality/responses');
      expect(res.status).toBe(500);
    });
  });
});